# General Jekyll Config
name: Ops Principles
description: A collection of principles, recipes, and case studies to help build great systems!
pygments: true
url: http://opsprincipl.es
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]

repository: https://github.com/solarkennedy/opsprincipl.es
theme:
  highlight_color: '#3498db'

permalink: /:categories/:title/
