name: Ops Principles

description: A collection of principles, recipies, and case studies to help build great systems

repository: https://github.com/solarkennedy/ops-principles

#url: http://

permalink: /:categories/:title/

exclude: [README.md]
